[2023-09-07T04:33:01.000+0000] {processor.py:157} INFO - Started process (PID=31) to work on /opt/airflow/dags/Orders_realPaidPrice.py
[2023-09-07T04:33:01.002+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/Orders_realPaidPrice.py for tasks to queue
[2023-09-07T04:33:01.005+0000] {logging_mixin.py:151} INFO - [2023-09-07T04:33:01.004+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/Orders_realPaidPrice.py
[2023-09-07T04:33:01.239+0000] {logging_mixin.py:151} INFO - [2023-09-07T04:33:01.237+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/Orders_realPaidPrice.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Orders_realPaidPrice.py", line 12, in <module>
    from read.ReadS3Orders import ReadS3OrdersData
  File "/opt/airflow/dags/read/ReadS3Orders.py", line 10, in <module>
    from CreateS3Orders import FileInformation
ModuleNotFoundError: No module named 'CreateS3Orders'
[2023-09-07T04:33:01.240+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/Orders_realPaidPrice.py
[2023-09-07T04:33:01.264+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/Orders_realPaidPrice.py took 0.267 seconds
[2023-09-07T04:33:31.786+0000] {processor.py:157} INFO - Started process (PID=42) to work on /opt/airflow/dags/Orders_realPaidPrice.py
[2023-09-07T04:33:31.786+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/Orders_realPaidPrice.py for tasks to queue
[2023-09-07T04:33:31.788+0000] {logging_mixin.py:151} INFO - [2023-09-07T04:33:31.788+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/Orders_realPaidPrice.py
[2023-09-07T04:33:31.850+0000] {logging_mixin.py:151} INFO - [2023-09-07T04:33:31.849+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/Orders_realPaidPrice.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Orders_realPaidPrice.py", line 12, in <module>
    from read.ReadS3Orders import ReadS3OrdersData
  File "/opt/airflow/dags/read/ReadS3Orders.py", line 10, in <module>
    from CreateS3Orders import FileInformation
ModuleNotFoundError: No module named 'CreateS3Orders'
[2023-09-07T04:33:31.850+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/Orders_realPaidPrice.py
[2023-09-07T04:33:31.868+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/Orders_realPaidPrice.py took 0.086 seconds
[2023-09-07T04:34:02.328+0000] {processor.py:157} INFO - Started process (PID=53) to work on /opt/airflow/dags/Orders_realPaidPrice.py
[2023-09-07T04:34:02.329+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/Orders_realPaidPrice.py for tasks to queue
[2023-09-07T04:34:02.331+0000] {logging_mixin.py:151} INFO - [2023-09-07T04:34:02.330+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/Orders_realPaidPrice.py
[2023-09-07T04:34:02.385+0000] {logging_mixin.py:151} INFO - [2023-09-07T04:34:02.384+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/Orders_realPaidPrice.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Orders_realPaidPrice.py", line 12, in <module>
    from read.ReadS3Orders import ReadS3OrdersData
  File "/opt/airflow/dags/read/ReadS3Orders.py", line 10, in <module>
    from CreateS3Orders import FileInformation
ModuleNotFoundError: No module named 'CreateS3Orders'
[2023-09-07T04:34:02.386+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/Orders_realPaidPrice.py
[2023-09-07T04:34:02.401+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/Orders_realPaidPrice.py took 0.076 seconds
[2023-09-07T04:34:32.901+0000] {processor.py:157} INFO - Started process (PID=64) to work on /opt/airflow/dags/Orders_realPaidPrice.py
[2023-09-07T04:34:32.902+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/Orders_realPaidPrice.py for tasks to queue
[2023-09-07T04:34:32.904+0000] {logging_mixin.py:151} INFO - [2023-09-07T04:34:32.904+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/Orders_realPaidPrice.py
[2023-09-07T04:34:32.964+0000] {logging_mixin.py:151} INFO - [2023-09-07T04:34:32.962+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/Orders_realPaidPrice.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Orders_realPaidPrice.py", line 12, in <module>
    from read.ReadS3Orders import ReadS3OrdersData
  File "/opt/airflow/dags/read/ReadS3Orders.py", line 10, in <module>
    from CreateS3Orders import FileInformation
ModuleNotFoundError: No module named 'CreateS3Orders'
[2023-09-07T04:34:32.964+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/Orders_realPaidPrice.py
[2023-09-07T04:34:32.980+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/Orders_realPaidPrice.py took 0.082 seconds
[2023-09-07T04:35:03.426+0000] {processor.py:157} INFO - Started process (PID=75) to work on /opt/airflow/dags/Orders_realPaidPrice.py
[2023-09-07T04:35:03.427+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/Orders_realPaidPrice.py for tasks to queue
[2023-09-07T04:35:03.430+0000] {logging_mixin.py:151} INFO - [2023-09-07T04:35:03.430+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/Orders_realPaidPrice.py
[2023-09-07T04:35:03.490+0000] {logging_mixin.py:151} INFO - [2023-09-07T04:35:03.488+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/Orders_realPaidPrice.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Orders_realPaidPrice.py", line 12, in <module>
    from read.ReadS3Orders import ReadS3OrdersData
  File "/opt/airflow/dags/read/ReadS3Orders.py", line 10, in <module>
    from CreateS3Orders import FileInformation
ModuleNotFoundError: No module named 'CreateS3Orders'
[2023-09-07T04:35:03.490+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/Orders_realPaidPrice.py
[2023-09-07T04:35:03.505+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/Orders_realPaidPrice.py took 0.084 seconds
[2023-09-07T04:35:34.035+0000] {processor.py:157} INFO - Started process (PID=86) to work on /opt/airflow/dags/Orders_realPaidPrice.py
[2023-09-07T04:35:34.037+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/Orders_realPaidPrice.py for tasks to queue
[2023-09-07T04:35:34.042+0000] {logging_mixin.py:151} INFO - [2023-09-07T04:35:34.041+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/Orders_realPaidPrice.py
[2023-09-07T04:35:34.106+0000] {logging_mixin.py:151} INFO - [2023-09-07T04:35:34.105+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/Orders_realPaidPrice.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Orders_realPaidPrice.py", line 12, in <module>
    from read.ReadS3Orders import ReadS3OrdersData
  File "/opt/airflow/dags/read/ReadS3Orders.py", line 10, in <module>
    from CreateS3Orders import FileInformation
ModuleNotFoundError: No module named 'CreateS3Orders'
[2023-09-07T04:35:34.107+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/Orders_realPaidPrice.py
[2023-09-07T04:35:34.123+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/Orders_realPaidPrice.py took 0.093 seconds
[2023-09-07T04:35:45.358+0000] {processor.py:157} INFO - Started process (PID=90) to work on /opt/airflow/dags/Orders_realPaidPrice.py
[2023-09-07T04:35:45.359+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/Orders_realPaidPrice.py for tasks to queue
[2023-09-07T04:35:45.361+0000] {logging_mixin.py:151} INFO - [2023-09-07T04:35:45.361+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/Orders_realPaidPrice.py
[2023-09-07T04:35:45.437+0000] {logging_mixin.py:151} INFO - [2023-09-07T04:35:45.432+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/Orders_realPaidPrice.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Orders_realPaidPrice.py", line 19, in <module>
    from ReadMongoOrders import DataLoad
ModuleNotFoundError: No module named 'ReadMongoOrders'
[2023-09-07T04:35:45.438+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/Orders_realPaidPrice.py
[2023-09-07T04:35:45.453+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/Orders_realPaidPrice.py took 0.097 seconds
[2023-09-07T04:55:27.702+0000] {processor.py:157} INFO - Started process (PID=32) to work on /opt/airflow/dags/Orders_realPaidPrice.py
[2023-09-07T04:55:27.704+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/Orders_realPaidPrice.py for tasks to queue
[2023-09-07T04:55:27.706+0000] {logging_mixin.py:151} INFO - [2023-09-07T04:55:27.706+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/Orders_realPaidPrice.py
[2023-09-07T04:55:27.720+0000] {logging_mixin.py:151} INFO - [2023-09-07T04:55:27.718+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/Orders_realPaidPrice.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Orders_realPaidPrice.py", line 20, in <module>
    from plugins.read.ReadS3Orders import ReadS3OrdersData
ModuleNotFoundError: No module named 'plugins'
[2023-09-07T04:55:27.720+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/Orders_realPaidPrice.py
[2023-09-07T04:55:27.736+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/Orders_realPaidPrice.py took 0.037 seconds
[2023-09-07T04:55:58.010+0000] {processor.py:157} INFO - Started process (PID=40) to work on /opt/airflow/dags/Orders_realPaidPrice.py
[2023-09-07T04:55:58.011+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/Orders_realPaidPrice.py for tasks to queue
[2023-09-07T04:55:58.013+0000] {logging_mixin.py:151} INFO - [2023-09-07T04:55:58.013+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/Orders_realPaidPrice.py
[2023-09-07T04:55:58.022+0000] {logging_mixin.py:151} INFO - [2023-09-07T04:55:58.020+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/Orders_realPaidPrice.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Orders_realPaidPrice.py", line 20, in <module>
    from plugins.read.ReadS3Orders import ReadS3OrdersData
ModuleNotFoundError: No module named 'plugins'
[2023-09-07T04:55:58.022+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/Orders_realPaidPrice.py
[2023-09-07T04:55:58.039+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/Orders_realPaidPrice.py took 0.033 seconds
[2023-09-07T04:56:28.395+0000] {processor.py:157} INFO - Started process (PID=48) to work on /opt/airflow/dags/Orders_realPaidPrice.py
[2023-09-07T04:56:28.396+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/Orders_realPaidPrice.py for tasks to queue
[2023-09-07T04:56:28.397+0000] {logging_mixin.py:151} INFO - [2023-09-07T04:56:28.397+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/Orders_realPaidPrice.py
[2023-09-07T04:56:28.403+0000] {logging_mixin.py:151} INFO - [2023-09-07T04:56:28.402+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/Orders_realPaidPrice.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Orders_realPaidPrice.py", line 20, in <module>
    from plugins.read.ReadS3Orders import ReadS3OrdersData
ModuleNotFoundError: No module named 'plugins'
[2023-09-07T04:56:28.403+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/Orders_realPaidPrice.py
[2023-09-07T04:56:28.421+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/Orders_realPaidPrice.py took 0.029 seconds
[2023-09-07T08:05:49.692+0000] {processor.py:157} INFO - Started process (PID=100) to work on /opt/airflow/dags/Orders_realPaidPrice.py
[2023-09-07T08:05:49.693+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/Orders_realPaidPrice.py for tasks to queue
[2023-09-07T08:05:49.694+0000] {logging_mixin.py:151} INFO - [2023-09-07T08:05:49.694+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/Orders_realPaidPrice.py
[2023-09-07T08:05:49.699+0000] {logging_mixin.py:151} INFO - [2023-09-07T08:05:49.698+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/Orders_realPaidPrice.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Orders_realPaidPrice.py", line 2, in <module>
    from plugins.create.CreateS3Orders import S3_WriteData
ModuleNotFoundError: No module named 'plugins'
[2023-09-07T08:05:49.700+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/Orders_realPaidPrice.py
[2023-09-07T08:05:49.715+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/Orders_realPaidPrice.py took 0.025 seconds
[2023-09-07T08:06:01.817+0000] {processor.py:157} INFO - Started process (PID=101) to work on /opt/airflow/dags/Orders_realPaidPrice.py
[2023-09-07T08:06:01.818+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/Orders_realPaidPrice.py for tasks to queue
[2023-09-07T08:06:01.820+0000] {logging_mixin.py:151} INFO - [2023-09-07T08:06:01.820+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/Orders_realPaidPrice.py
[2023-09-07T08:06:01.828+0000] {logging_mixin.py:151} INFO - [2023-09-07T08:06:01.827+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/Orders_realPaidPrice.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Orders_realPaidPrice.py", line 2, in <module>
    from plugins.create.CreateS3Orders import S3_WriteData
ModuleNotFoundError: No module named 'plugins'
[2023-09-07T08:06:01.829+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/Orders_realPaidPrice.py
[2023-09-07T08:06:01.845+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/Orders_realPaidPrice.py took 0.030 seconds
[2023-09-07T08:06:32.104+0000] {processor.py:157} INFO - Started process (PID=109) to work on /opt/airflow/dags/Orders_realPaidPrice.py
[2023-09-07T08:06:32.104+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/Orders_realPaidPrice.py for tasks to queue
[2023-09-07T08:06:32.107+0000] {logging_mixin.py:151} INFO - [2023-09-07T08:06:32.106+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/Orders_realPaidPrice.py
[2023-09-07T08:06:32.111+0000] {logging_mixin.py:151} INFO - [2023-09-07T08:06:32.111+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/Orders_realPaidPrice.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Orders_realPaidPrice.py", line 2, in <module>
    from plugins.create.CreateS3Orders import S3_WriteData
ModuleNotFoundError: No module named 'plugins'
[2023-09-07T08:06:32.112+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/Orders_realPaidPrice.py
[2023-09-07T08:06:32.127+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/Orders_realPaidPrice.py took 0.027 seconds
[2023-09-07T08:06:35.164+0000] {processor.py:157} INFO - Started process (PID=110) to work on /opt/airflow/dags/Orders_realPaidPrice.py
[2023-09-07T08:06:35.166+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/Orders_realPaidPrice.py for tasks to queue
[2023-09-07T08:06:35.168+0000] {logging_mixin.py:151} INFO - [2023-09-07T08:06:35.167+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/Orders_realPaidPrice.py
[2023-09-07T08:06:35.176+0000] {logging_mixin.py:151} INFO - [2023-09-07T08:06:35.175+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/Orders_realPaidPrice.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Orders_realPaidPrice.py", line 2, in <module>
    from create.CreateS3Orders import S3_WriteData
  File "/opt/airflow/plugins/create/CreateS3Orders.py", line 6, in <module>
    from plugins.read.ReadMongoOrders import DataLoad
ModuleNotFoundError: No module named 'plugins'
[2023-09-07T08:06:35.176+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/Orders_realPaidPrice.py
[2023-09-07T08:06:35.192+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/Orders_realPaidPrice.py took 0.034 seconds
[2023-09-07T08:07:05.494+0000] {processor.py:157} INFO - Started process (PID=118) to work on /opt/airflow/dags/Orders_realPaidPrice.py
[2023-09-07T08:07:05.495+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/Orders_realPaidPrice.py for tasks to queue
[2023-09-07T08:07:05.498+0000] {logging_mixin.py:151} INFO - [2023-09-07T08:07:05.497+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/Orders_realPaidPrice.py
[2023-09-07T08:07:05.505+0000] {logging_mixin.py:151} INFO - [2023-09-07T08:07:05.504+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/Orders_realPaidPrice.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Orders_realPaidPrice.py", line 2, in <module>
    from create.CreateS3Orders import S3_WriteData
  File "/opt/airflow/plugins/create/CreateS3Orders.py", line 6, in <module>
    from plugins.read.ReadMongoOrders import DataLoad
ModuleNotFoundError: No module named 'plugins'
[2023-09-07T08:07:05.506+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/Orders_realPaidPrice.py
[2023-09-07T08:07:05.528+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/Orders_realPaidPrice.py took 0.036 seconds
[2023-09-07T08:07:35.817+0000] {processor.py:157} INFO - Started process (PID=126) to work on /opt/airflow/dags/Orders_realPaidPrice.py
[2023-09-07T08:07:35.818+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/Orders_realPaidPrice.py for tasks to queue
[2023-09-07T08:07:35.820+0000] {logging_mixin.py:151} INFO - [2023-09-07T08:07:35.819+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/Orders_realPaidPrice.py
[2023-09-07T08:07:35.827+0000] {logging_mixin.py:151} INFO - [2023-09-07T08:07:35.826+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/Orders_realPaidPrice.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Orders_realPaidPrice.py", line 2, in <module>
    from create.CreateS3Orders import S3_WriteData
  File "/opt/airflow/plugins/create/CreateS3Orders.py", line 6, in <module>
    from plugins.read.ReadMongoOrders import DataLoad
ModuleNotFoundError: No module named 'plugins'
[2023-09-07T08:07:35.827+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/Orders_realPaidPrice.py
[2023-09-07T08:07:35.844+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/Orders_realPaidPrice.py took 0.029 seconds
[2023-09-07T08:07:46.961+0000] {processor.py:157} INFO - Started process (PID=134) to work on /opt/airflow/dags/Orders_realPaidPrice.py
[2023-09-07T08:07:46.963+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/Orders_realPaidPrice.py for tasks to queue
[2023-09-07T08:07:46.967+0000] {logging_mixin.py:151} INFO - [2023-09-07T08:07:46.966+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/Orders_realPaidPrice.py
[2023-09-07T08:07:46.981+0000] {logging_mixin.py:151} INFO - [2023-09-07T08:07:46.979+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/Orders_realPaidPrice.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Orders_realPaidPrice.py", line 2, in <module>
    from create.CreateS3Orders import S3_WriteData
  File "/opt/airflow/plugins/create/CreateS3Orders.py", line 6, in <module>
    from plugins.read.ReadMongoOrders import DataLoad
ModuleNotFoundError: No module named 'plugins'
[2023-09-07T08:07:46.982+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/Orders_realPaidPrice.py
[2023-09-07T08:07:47.004+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/Orders_realPaidPrice.py took 0.047 seconds
[2023-09-07T08:08:17.308+0000] {processor.py:157} INFO - Started process (PID=142) to work on /opt/airflow/dags/Orders_realPaidPrice.py
[2023-09-07T08:08:17.309+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/Orders_realPaidPrice.py for tasks to queue
[2023-09-07T08:08:17.311+0000] {logging_mixin.py:151} INFO - [2023-09-07T08:08:17.311+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/Orders_realPaidPrice.py
[2023-09-07T08:08:17.317+0000] {logging_mixin.py:151} INFO - [2023-09-07T08:08:17.316+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/Orders_realPaidPrice.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Orders_realPaidPrice.py", line 2, in <module>
    from create.CreateS3Orders import S3_WriteData
  File "/opt/airflow/plugins/create/CreateS3Orders.py", line 6, in <module>
    from plugins.read.ReadMongoOrders import DataLoad
ModuleNotFoundError: No module named 'plugins'
[2023-09-07T08:08:17.317+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/Orders_realPaidPrice.py
[2023-09-07T08:08:17.334+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/Orders_realPaidPrice.py took 0.028 seconds
[2023-09-07T08:08:47.621+0000] {processor.py:157} INFO - Started process (PID=150) to work on /opt/airflow/dags/Orders_realPaidPrice.py
[2023-09-07T08:08:47.622+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/Orders_realPaidPrice.py for tasks to queue
[2023-09-07T08:08:47.623+0000] {logging_mixin.py:151} INFO - [2023-09-07T08:08:47.623+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/Orders_realPaidPrice.py
[2023-09-07T08:08:47.629+0000] {logging_mixin.py:151} INFO - [2023-09-07T08:08:47.628+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/Orders_realPaidPrice.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Orders_realPaidPrice.py", line 2, in <module>
    from create.CreateS3Orders import S3_WriteData
  File "/opt/airflow/plugins/create/CreateS3Orders.py", line 6, in <module>
    from plugins.read.ReadMongoOrders import DataLoad
ModuleNotFoundError: No module named 'plugins'
[2023-09-07T08:08:47.630+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/Orders_realPaidPrice.py
[2023-09-07T08:08:47.645+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/Orders_realPaidPrice.py took 0.027 seconds
[2023-09-07T08:09:17.895+0000] {processor.py:157} INFO - Started process (PID=158) to work on /opt/airflow/dags/Orders_realPaidPrice.py
[2023-09-07T08:09:17.896+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/Orders_realPaidPrice.py for tasks to queue
[2023-09-07T08:09:17.898+0000] {logging_mixin.py:151} INFO - [2023-09-07T08:09:17.897+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/Orders_realPaidPrice.py
[2023-09-07T08:09:17.904+0000] {logging_mixin.py:151} INFO - [2023-09-07T08:09:17.903+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/Orders_realPaidPrice.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Orders_realPaidPrice.py", line 2, in <module>
    from create.CreateS3Orders import S3_WriteData
  File "/opt/airflow/plugins/create/CreateS3Orders.py", line 6, in <module>
    from plugins.read.ReadMongoOrders import DataLoad
ModuleNotFoundError: No module named 'plugins'
[2023-09-07T08:09:17.905+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/Orders_realPaidPrice.py
[2023-09-07T08:09:17.921+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/Orders_realPaidPrice.py took 0.029 seconds
